version: '3'
services:
  ntsimulator:
    image: "o-ran-sc_ntsim_manager:latest"
    container_name: NTS_Manager
    ports:
     - "8300:830"
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "/home/parallels/workspace/highstreet/o-ran-sc-repositories/o1-interface/ntsimulator/scripts:/opt/dev/scripts"
     - "/usr/bin/docker:/usr/bin/docker"
    labels:
      "NTS-manager": ""
    environment:
      NTS_IP: "172.17.0.1"
      NETCONF_BASE: 50000
      DOCKER_ENGINE_VERSION: "1.40"
      MODELS_IMAGE: "o-ran-sc_ntsim_oran"

